apiVersion: v1
kind: Service
metadata:
  labels:
    app: linknest-backend
  name: linknest-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    protocol: TCP
    targetPort: 8000
  selector:
    app: linknest-backend
  type: {{ .Values.backend.service.type }}
