apiVersion: v1
kind: Service
metadata:
  labels:
    app: linknest-backend
  name: linknest-backend
  namespace: linknest-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: linknest-backend
  type: ClusterIP
