apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.database.config.postgresDb }}
  POSTGRES_SERVICE: database-svc
  POSTGRES_USER: {{ .Values.database.config.postgresUser }}
kind: ConfigMap
metadata:
  name: linknest-config
  namespace: {{ .Values.namespace }}
