apiVersion: v1
kind: Service
metadata:
  labels:
    app: linknest-frontend
  name: linknest-frontend
  namespace: linknest-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: linknest-frontend
  type: ClusterIP
